# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PictureDetection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtGui import QStandardItemModel, QPalette, QColor
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QHeaderView


class PictureDetectionWin(QWidget):
    def setupUi(self, PictureDetection):
        PictureDetection.setObjectName("PictureDetection")
        PictureDetection.resize(988, 828)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(PictureDetection)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.original_picture_label = QtWidgets.QLabel(PictureDetection)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.original_picture_label.setFont(font)
        self.original_picture_label.setObjectName("original_picture_label")
        self.verticalLayout.addWidget(self.original_picture_label)
        self.origin_scrollArea = QtWidgets.QScrollArea(PictureDetection)
        self.origin_scrollArea.setWidgetResizable(True)
        self.origin_scrollArea.setObjectName("origin_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 427, 349))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout1 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.origin_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.origin_scrollArea)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.detection_picture_label = QtWidgets.QLabel(PictureDetection)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.detection_picture_label.setFont(font)
        self.detection_picture_label.setObjectName("detection_picture_label")
        self.verticalLayout_2.addWidget(self.detection_picture_label)
        self.detection_scrollArea = QtWidgets.QScrollArea()
        self.detection_scrollArea.setWidgetResizable(True)
        self.detection_scrollArea.setObjectName("detection_scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 426, 349))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.detection_scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.detection_scrollArea)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 6)
        self.horizontalLayout.setStretch(1, 6)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.model = QStandardItemModel(0, 2);

        self.model.setHorizontalHeaderLabels(['图片编号','缺陷类型'])
        self.resultView = QtWidgets.QTableView()
        self.resultView.setModel(self.model)
        self.resultView.setObjectName("resultView")
        self.resultView.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.verticalLayout_3.addWidget(self.resultView)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem1)
        self.stop = QtWidgets.QPushButton(PictureDetection)
        self.stop.setMinimumSize(QtCore.QSize(91, 41))
        self.stop.setObjectName("stop")
        self.verticalLayout_4.addWidget(self.stop)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem2)
        self.start = QtWidgets.QPushButton(PictureDetection)
        self.start.setMinimumSize(QtCore.QSize(91, 41))
        self.start.setObjectName("start")
        self.verticalLayout_4.addWidget(self.start)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem3)
        self.open = QtWidgets.QPushButton(PictureDetection)
        self.open.setMinimumSize(QtCore.QSize(91, 41))
        self.open.setObjectName("open")
        self.verticalLayout_4.addWidget(self.open)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.retranslateUi(PictureDetection)
        QtCore.QMetaObject.connectSlotsByName(PictureDetection)

    def retranslateUi(self, PictureDetection):
        _translate = QtCore.QCoreApplication.translate
        PictureDetection.setWindowTitle(_translate("PictureDetection", "Form"))
        self.original_picture_label.setText(_translate("PictureDetection", "原图"))
        self.detection_picture_label.setText(_translate("PictureDetection", "检测图"))
        self.stop.setText(_translate("PictureDetection", "stop"))
        self.start.setText(_translate("PictureDetection", "start"))
        self.open.setText(_translate("PictureDetection", "open"))
        pe = QPalette()
        PictureDetection.setAutoFillBackground(True)
        pe.setColor(QPalette.Window, QColor("#5A5A5A"))  # 设置背景色
        PictureDetection.setPalette(pe)