# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataSetWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtGui import QPalette, QColor, QIcon, QPixmap
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

class DataSetWin(QWidget):
    def setupUi(self, DataSet):
        DataSet.setObjectName("DataSet")
        DataSet.resize(583, 407)
        self.title = QtWidgets.QLabel(DataSet)
        self.title.setGeometry(QtCore.QRect(240, 12, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.tip = QtWidgets.QLabel(DataSet)
        self.tip.setGeometry(QtCore.QRect(120, 60, 350, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tip.setFont(font)
        self.tip.setStyleSheet("color:red")
        self.tip.setObjectName("tip")
        self.classes = QtWidgets.QTextEdit(DataSet)
        self.classes.setGeometry(QtCore.QRect(130, 100, 331, 111))
        self.classes.setObjectName("classes")
        self.classes_label = QtWidgets.QLabel(DataSet)
        self.classes_label.setGeometry(QtCore.QRect(30, 120, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.classes_label.setFont(font)
        self.classes_label.setObjectName("classes_label")
        self.confirm = QtWidgets.QPushButton(DataSet)
        self.confirm.setGeometry(QtCore.QRect(310, 240, 81, 31))
        self.confirm.setObjectName("confirm")
        self.cancel = QtWidgets.QPushButton(DataSet)
        self.cancel.setGeometry(QtCore.QRect(410, 240, 71, 31))
        self.cancel.setObjectName("cancel")


        self.retranslateUi(DataSet)
        QtCore.QMetaObject.connectSlotsByName(DataSet)

    def retranslateUi(self,DataSet):
        _translate = QtCore.QCoreApplication.translate
        DataSet.setWindowTitle(_translate("DataSet", "Dialog"))
        self.title.setText(_translate("DataSet", "生成数据集"))
        self.tip.setText(_translate("DataSet", "提示：请先确认是否已完成数据的采样和标注"))
        self.classes_label.setText(_translate("DataSet", "classes:"))
        self.confirm.setText(_translate("DataSet", "确定"))
        self.cancel.setText(_translate("DataSet", "取消"))
        self.setWindowTitle("生成数据集")
        icon = QIcon()
        icon.addPixmap(QPixmap("../resource/logo3.ico"))
        self.setWindowIcon(icon)
        pe = QPalette()
        DataSet.setAutoFillBackground(True)
        pe.setColor(QPalette.Window, QColor("#5A5A5A"))  # 设置背景色
        DataSet.setPalette(pe)
