# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TrainMainWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDesktopWidget


class Ui_TrainMainWindow(object):
    def setupUi(self, TrainMainWindow):
        TrainMainWindow.setObjectName("TrainMainWindow")
        TrainMainWindow.resize(1012, 728)
        font = QtGui.QFont()
        font.setPointSize(9)
        TrainMainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(TrainMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(530, 10, 451, 631))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 411, 591))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 471, 621))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(14, 29, 261, 201))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(29, 55, 421, 241))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setGeometry(QtCore.QRect(10, 320, 451, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 360, 421, 241))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(490, 10, 20, 641))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        TrainMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(TrainMainWindow)
        self.statusbar.setObjectName("statusbar")
        TrainMainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(TrainMainWindow)
        self.toolBar.setObjectName("toolBar")
        TrainMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtWidgets.QMenuBar(TrainMainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1012, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuSetting = QtWidgets.QMenu(self.menuBar)
        self.menuSetting.setObjectName("menuSetting")
        TrainMainWindow.setMenuBar(self.menuBar)
        self.actionDetection = QtWidgets.QAction(TrainMainWindow)
        self.actionDetection.setObjectName("actionDetection")
        self.actionTrain = QtWidgets.QAction(TrainMainWindow)
        self.actionTrain.setObjectName("actionTrain")
        self.actionMark = QtWidgets.QAction(TrainMainWindow)
        self.actionMark.setObjectName("actionMark")
        self.actionopen = QtWidgets.QAction(TrainMainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionstart = QtWidgets.QAction(TrainMainWindow)
        self.actionstart.setObjectName("actionstart")
        self.actionstop = QtWidgets.QAction(TrainMainWindow)
        self.actionstop.setObjectName("actionstop")
        self.actionimport = QtWidgets.QAction(TrainMainWindow)
        self.actionimport.setObjectName("actionimport")
        self.actionparam = QtWidgets.QAction(TrainMainWindow)
        self.actionparam.setObjectName("actionparam")
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDetection)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionTrain)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionMark)
        self.toolBar.addSeparator()
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionopen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionimport)
        self.menuSetting.addAction(self.actionstart)
        self.menuSetting.addSeparator()
        self.menuSetting.addAction(self.actionstop)
        self.menuSetting.addSeparator()
        self.menuSetting.addAction(self.actionparam)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSetting.menuAction())

        self.retranslateUi(TrainMainWindow)
        QtCore.QMetaObject.connectSlotsByName(TrainMainWindow)
        self.center()
    def retranslateUi(self, TrainMainWindow):
        _translate = QtCore.QCoreApplication.translate
        TrainMainWindow.setWindowTitle(_translate("TrainMainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("TrainMainWindow", "训练过程"))
        self.groupBox_2.setTitle(_translate("TrainMainWindow", "曲线图"))
        self.toolBar.setWindowTitle(_translate("TrainMainWindow", "toolBar"))
        self.menuFile.setTitle(_translate("TrainMainWindow", "File"))
        self.menuSetting.setTitle(_translate("TrainMainWindow", "Setting"))
        self.actionDetection.setText(_translate("TrainMainWindow", "检测模式"))
        self.actionDetection.setToolTip(_translate("TrainMainWindow", "检测模式"))
        self.actionDetection.setShortcut(_translate("TrainMainWindow", "Ctrl+D"))
        self.actionTrain.setText(_translate("TrainMainWindow", "训练模式"))
        self.actionTrain.setToolTip(_translate("TrainMainWindow", "训练模式"))
        self.actionTrain.setShortcut(_translate("TrainMainWindow", "Ctrl+T"))
        self.actionMark.setText(_translate("TrainMainWindow", "标注模式"))
        self.actionMark.setToolTip(_translate("TrainMainWindow", "标注图片"))
        self.actionMark.setShortcut(_translate("TrainMainWindow", "Ctrl+M"))
        self.actionopen.setText(_translate("TrainMainWindow", "open"))
        self.actionstart.setText(_translate("TrainMainWindow", "start"))
        self.actionstop.setText(_translate("TrainMainWindow", "stop"))
        self.actionimport.setText(_translate("TrainMainWindow", "import"))
        self.actionparam.setText(_translate("TrainMainWindow", "param"))

    def center(self):
        screen = QDesktopWidget().screenGeometry()
        size = self.geometry()
        self.move((screen.width() - size.width()) / 2,
                  (screen.height() - size.height()) / 2)