from PyQt5.QtGui import QStandardItemModel, QPalette, QColor, QStandardItem
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDesktopWidget, QHeaderView,QWidget


class DetectionWin(QWidget):
    Margins = 5
    def setupUi(self, Detection):
        Detection.setObjectName("Detection")
        Detection.resize(1270, 870)
        font = QtGui.QFont()
        font.setPointSize(12)
        Detection.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Detection)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1251, 671))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.camera3 = QtWidgets.QWidget(self.layoutWidget)
        self.camera3.setObjectName("camera3")
        self.camera3_detection_label = QtWidgets.QLabel(self.camera3)
        self.camera3_detection_label.setGeometry(QtCore.QRect(80, 10, 440, 300))
        self.camera3_detection_label.setText("")
        self.camera3_detection_label.setObjectName("camera3_detection_label")
        self.camera3_label = QtWidgets.QLabel(self.camera3)
        self.camera3_label.setGeometry(QtCore.QRect(10, 10, 60, 20))
        self.camera3_label.setObjectName("camera3_label")
        self.camera3_result_label = QtWidgets.QLabel(self.camera3)
        self.camera3_result_label.setGeometry(QtCore.QRect(530, 10, 90, 40))
        self.camera3_result_label.setText("")
        self.camera3_result_label.setObjectName("camera3_result_label")
        self.gridLayout.addWidget(self.camera3, 1, 0, 1, 1)
        self.camera1 = QtWidgets.QWidget(self.layoutWidget)
        self.camera1.setObjectName("camera1")
        self.camera1_detection_label = QtWidgets.QLabel(self.camera1)
        self.camera1_detection_label.setGeometry(QtCore.QRect(80, 10, 440, 300))
        self.camera1_detection_label.setText("")
        self.camera1_detection_label.setObjectName("camera1_detection_label")
        self.camera1_label = QtWidgets.QLabel(self.camera1)
        self.camera1_label.setGeometry(QtCore.QRect(10, 10, 60, 20))
        self.camera1_label.setObjectName("camera1_label")
        self.camera1_result_label = QtWidgets.QLabel(self.camera1)
        self.camera1_result_label.setGeometry(QtCore.QRect(530, 10, 90, 40))
        self.camera1_result_label.setText("")
        self.camera1_result_label.setObjectName("camera1_result_label")
        self.gridLayout.addWidget(self.camera1, 0, 0, 1, 1)
        self.camera2 = QtWidgets.QWidget(self.layoutWidget)
        self.camera2.setObjectName("camera2")
        self.camera2_detection_label = QtWidgets.QLabel(self.camera2)
        self.camera2_detection_label.setGeometry(QtCore.QRect(80, 10, 440, 300))
        self.camera2_detection_label.setText("")
        self.camera2_detection_label.setObjectName("camera2_detection_label")
        self.camera2_label = QtWidgets.QLabel(self.camera2)
        self.camera2_label.setGeometry(QtCore.QRect(10, 10, 60, 20))
        self.camera2_label.setObjectName("camera2_label")
        self.camera2_result_label = QtWidgets.QLabel(self.camera2)
        self.camera2_result_label.setGeometry(QtCore.QRect(530, 10, 90, 40))
        self.camera2_result_label.setText("")
        self.camera2_result_label.setObjectName("camera2_result_label")
        self.gridLayout.addWidget(self.camera2, 0, 1, 1, 1)
        self.camera4 = QtWidgets.QWidget(self.layoutWidget)
        self.camera4.setObjectName("camera4")
        self.camera4_detection_label = QtWidgets.QLabel(self.camera4)
        self.camera4_detection_label.setGeometry(QtCore.QRect(80, 10, 440, 300))
        self.camera4_detection_label.setText("")
        self.camera4_detection_label.setObjectName("camera4_detection_label")
        self.camera4_label = QtWidgets.QLabel(self.camera4)
        self.camera4_label.setGeometry(QtCore.QRect(10, 10, 61, 21))
        self.camera4_label.setObjectName("camera4_label")
        self.camera4_result_label = QtWidgets.QLabel(self.camera4)
        self.camera4_result_label.setGeometry(QtCore.QRect(530, 10, 90, 40))
        self.camera4_result_label.setText("")
        self.camera4_result_label.setObjectName("camera4_result_label")
        self.gridLayout.addWidget(self.camera4, 1, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 680, 1251, 161))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.model = QStandardItemModel(4, 6);
        self.model.setHorizontalHeaderLabels(['相机', '检测数', '良品', '瑕疵品', '瑕疵率', '检测速度'])
        self.model.setItem(0, 0, QStandardItem("相机1号"))
        self.model.setItem(1, 0, QStandardItem("相机2号"))
        self.model.setItem(2, 0, QStandardItem("相机3号"))
        self.model.setItem(3, 0, QStandardItem("相机4号"))
        self.result_view = QtWidgets.QTableView(self.centralwidget)
        self.result_view.verticalHeader().hide()
        self.result_view.horizontalHeader().setStretchLastSection(True)
        self.result_view.verticalHeader().setStretchLastSection(True)
        self.result_view.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.result_view.verticalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.result_view.setModel(self.model)
        self.result_view.setGeometry(QtCore.QRect(15, 680, 650, 170))
        self.result_view.setObjectName("result_view")
        self.horizontalLayout.addWidget(self.result_view)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.product_name = QtWidgets.QLabel(self.widget)
        self.product_name.setObjectName("product_name")
        self.verticalLayout.addWidget(self.product_name)
        self.product_id = QtWidgets.QLabel(self.widget)
        self.product_id.setObjectName("product_id")
        self.verticalLayout.addWidget(self.product_id)
        self.detect_time = QtWidgets.QLabel(self.widget)
        self.detect_time.setObjectName("detect_time")
        self.verticalLayout.addWidget(self.detect_time)
        self.speed = QtWidgets.QLabel(self.widget)
        self.speed.setObjectName("speed")
        self.verticalLayout.addWidget(self.speed)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.operation_list = QtWidgets.QGroupBox(self.widget)
        self.operation_list.setTitle("")
        self.operation_list.setObjectName("operation_list")
        self.RedButton = QtWidgets.QPushButton(self.centralwidget)
        self.RedButton.setGeometry(QtCore.QRect(1130, 780, 110, 45))
        self.RedButton.setObjectName("RedButton")
        self.GreenButton = QtWidgets.QPushButton(self.centralwidget)
        self.GreenButton.setGeometry(QtCore.QRect(1130, 730, 110, 45))
        self.GreenButton.setObjectName("GreenButton")
        self.BlueButton = QtWidgets.QPushButton(self.centralwidget)
        self.BlueButton.setGeometry(QtCore.QRect(1130, 680, 110, 45))
        self.BlueButton.setObjectName("BlueButton")
        self.horizontalLayout.addWidget(self.operation_list)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 1)
        self.retranslateUi(Detection)
        QtCore.QMetaObject.connectSlotsByName(Detection)
        self.center()
    def retranslateUi(self, QWidget):
        _translate = QtCore.QCoreApplication.translate
        QWidget.setWindowTitle(_translate("QWidget", "QWidget"))
        self.camera3_label.setText(_translate("QWidget", "3号相机"))
        self.camera1_label.setText(_translate("QWidget", "1号相机"))
        self.camera2_label.setText(_translate("QWidget", "2号相机"))
        self.camera4_label.setText(_translate("QWidget", "4号相机"))
        self.product_name.setText(_translate("QWidget", "产品名称:"))
        self.product_id.setText(_translate("QWidget", "产品批次:"))
        self.detect_time.setText(_translate("QWidget", "检测时间："))
        self.speed.setText(_translate("QWidget", "运行速度："))
        self.RedButton.setText(_translate("QWidget", "停止"))
        self.GreenButton.setText(_translate("QWidget", "运行"))
        self.BlueButton.setText(_translate("QWidget", "复位"))
        pe = QPalette()
        QWidget.setAutoFillBackground(True)
        pe.setColor(QPalette.Window, QColor("#5A5A5A"))  # 设置背景色
        QWidget.setPalette(pe)
    def center(self):
        screen = QDesktopWidget().screenGeometry()
        size = self.geometry()
        self.move((screen.width() - size.width()) / 2,
                  (screen.height() - size.height()) / 2)