# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDesktopWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1012, 728)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 991, 651))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 30, 421, 291))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_4.addWidget(self.checkBox)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 320, 974, 324))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 30, 421, 291))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_6.addWidget(self.checkBox_2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.carmer_detection_label1 = QtWidgets.QLabel(self.groupBox_3)
        self.carmer_detection_label1.setGeometry(QtCore.QRect(529, 51, 411, 261))
        self.carmer_detection_label1.setText("")
        self.carmer_detection_label1.setObjectName("carmer_detection_label1")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(520, 30, 201, 21))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.defect_type_label1 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.defect_type_label1.setFont(font)
        self.defect_type_label1.setObjectName("defect_type_label1")
        self.horizontalLayout_3.addWidget(self.defect_type_label1)
        self.show_defect_type_label1 = QtWidgets.QLabel(self.layoutWidget_3)
        self.show_defect_type_label1.setText("")
        self.show_defect_type_label1.setObjectName("show_defect_type_label1")
        self.horizontalLayout_3.addWidget(self.show_defect_type_label1)
        self.carmer_detection_label = QtWidgets.QLabel(self.groupBox_2)
        self.carmer_detection_label.setGeometry(QtCore.QRect(529, 51, 411, 261))
        self.carmer_detection_label.setText("")
        self.carmer_detection_label.setObjectName("carmer_detection_label")
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(520, 30, 201, 21))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.defect_type_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.defect_type_label.setFont(font)
        self.defect_type_label.setObjectName("defect_type_label")
        self.horizontalLayout_2.addWidget(self.defect_type_label)
        self.show_defect_type_label = QtWidgets.QLabel(self.widget)
        self.show_defect_type_label.setText("")
        self.show_defect_type_label.setObjectName("show_defect_type_label")
        self.horizontalLayout_2.addWidget(self.show_defect_type_label)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.horizontalLayout.setStretch(0, 8)
        self.horizontalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1012, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuRun = QtWidgets.QMenu(self.menuBar)
        self.menuRun.setObjectName("menuRun")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menuBar)
        self.actionDetection = QtWidgets.QAction(MainWindow)
        self.actionDetection.setObjectName("actionDetection")
        self.actionTrain = QtWidgets.QAction(MainWindow)
        self.actionTrain.setObjectName("actionTrain")
        self.actionMark = QtWidgets.QAction(MainWindow)
        self.actionMark.setObjectName("actionMark")
        self.actionRun = QtWidgets.QAction(MainWindow)
        self.actionRun.setObjectName("actionRun")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionpicture_detection = QtWidgets.QAction(MainWindow)
        self.actionpicture_detection.setObjectName("actionpicture_detection")
        self.actionreal_time_detection = QtWidgets.QAction(MainWindow)
        self.actionreal_time_detection.setObjectName("actionreal_time_detection")
        self.actionbatch_detection = QtWidgets.QAction(MainWindow)
        self.actionbatch_detection.setObjectName("actionbatch_detection")
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDetection)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionTrain)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionMark)
        self.toolBar.addSeparator()
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionRun)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionStop)
        self.menuSettings.addAction(self.actionreal_time_detection)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionpicture_detection)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionbatch_detection)
        self.menuBar.addAction(self.menuRun.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.center()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "缺陷检测系统"))
        self.groupBox_2.setTitle(_translate("MainWindow", "    相机1"))
        self.checkBox.setText(_translate("MainWindow", "开启"))
        self.groupBox_3.setTitle(_translate("MainWindow", "   相机2"))
        self.checkBox_2.setText(_translate("MainWindow", "开启"))
        self.defect_type_label1.setText(_translate("MainWindow", "缺陷类型:"))
        self.defect_type_label.setText(_translate("MainWindow", "缺陷类型:"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menuRun.setTitle(_translate("MainWindow", "Run"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionDetection.setText(_translate("MainWindow", "检测模式"))
        self.actionDetection.setToolTip(_translate("MainWindow", "检测模式"))
        self.actionDetection.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionTrain.setText(_translate("MainWindow", "训练模式"))
        self.actionTrain.setToolTip(_translate("MainWindow", "训练模式"))
        self.actionTrain.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionMark.setText(_translate("MainWindow", "标注模式"))
        self.actionMark.setToolTip(_translate("MainWindow", "标注图片"))
        self.actionMark.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionRun.setText(_translate("MainWindow", "Run"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionpicture_detection.setText(_translate("MainWindow", "picture detection"))
        self.actionreal_time_detection.setText(_translate("MainWindow", "real-time detection"))
        self.actionbatch_detection.setText(_translate("MainWindow", "batch detection"))
    def center(self):
        screen = QDesktopWidget().screenGeometry()
        size = self.geometry()
        self.move((screen.width() - size.width()) / 2,
                  (screen.height() - size.height()) / 2)
